# -*- coding: utf-8 -*-
"""corrected_python

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13i5cnF_tMM1bXSjYrMHYpTYsEKp1AJXf
"""

# Commented out IPython magic to ensure Python compatibility.
# %%writefile student_utils.py
# 
# PASS_MARK = 40
# 
# def calculate_average(marks):
#     total = 0
# 
#     for m in marks:
#         total = total + m
# 
#     return total / (len(marks))
# 
# 
# def is_passing(mark):
#     if mark >= PASS_MARK:
#         return True
# 
#     return False
# 
# 
# def get_grade(average):
#   if average >= 90:
#         return "Distinction"
#   elif average >= 60:
#         return "First"
# 
#   elif average >= 45:
#         return "Second"
# 
# 
#     return "Fail"

print(calculate_average([80, 90, 100]))

# Commented out IPython magic to ensure Python compatibility.
# %%writefile test_student_utils.py
# 
# import unittest
# 
# from student_utils import calculate_average, is_passing, get_grade
# 
# 
# class TestStudentUtils(unittest.TestCase):
# 
#     def test_average_of_three_marks(self):
#         self.assertEqual(
#             calculate_average([80, 90, 100]),
#             90.0
#         )
# 
#     def test_average_single_mark(self):
#         self.assertEqual(
#             calculate_average([40]),
#             40.0
#         )
# 
#     def test_above_pass_mark(self):
#         self.assertEqual(is_passing(41), True)
# 
#     def test_exact_pass_mark(self):
#         self.assertEqual(is_passing(40), True)
# 
#     def test_below_pass_mark(self):
#         self.assertEqual(is_passing(39), False)
# 
#     def test_distinction(self):
#         self.assertEqual(get_grade(95), "Distinction")
# 
#     def test_first(self):
#         self.assertEqual(get_grade(60), "First")
# 
#     def test_second(self):
#         self.assertEqual(get_grade(45), "Second")
# 
#     def test_fail(self):
#         self.assertEqual(get_grade(30), "Fail")
# 
# 
# if __name__ == "__main__":
#     unittest.main()

!python test_student_utils.py