# -*- coding: utf-8 -*-
"""testfile

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1eCiNkmdSnogZ6umfO-xn8N8MiT46bNOs
"""

import unittest

from student_utils import calculate_average, is_passing, get_grade


class TestStudentUtils(unittest.TestCase):

    def test_average_of_three_marks(self):
        self.assertEqual(
            calculate_average([80, 90, 100]),
            90.0
        )

    def test_average_single_mark(self):
        self.assertEqual(
            calculate_average([40]),
            40.0
        )

    def test_mark_above_pass_mark(self):
        self.assertEqual(
            is_passing(41),
            True
        )

    def test_mark_at_pass_mark(self):
        self.assertEqual(
            is_passing(40),
            True
        )

    def test_mark_below_pass_mark(self):
        self.assertEqual(
            is_passing(39),
            False
        )

    def test_distinction_grade(self):
        self.assertEqual(
            get_grade(95),
            "Distinction"
        )

    def test_first_grade(self):
        self.assertEqual(
            get_grade(60),
            "First"
        )

    def test_second_grade(self):
        self.assertEqual(
            get_grade(45),
            "Second"
        )

    def test_fail_grade(self):
        self.assertEqual(
            get_grade(30),
            "Fail"
        )


unittest.main(argv=[""], exit=False)